name: coverage

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  cover:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: '1.15'
      - uses: actions/checkout@v2
      - run: go test -v -coverprofile=.cover/cover.out ./...

      - name: Send coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: .cover/cover.out

  # notifies that all test jobs are finished.
  # finish:
  #   needs: cover
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: shogo82148/actions-goveralls@v1
  #       with:
  #         parallel-finished: true